name: Build Revanced APK
# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build-apk:
    name: APK Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Update Env for custom build
        run: |
          echo "${{ secrets.ENVS }}" >> .env

      - name: Build Revanced APKs
        run: |
          docker-compose up

      - name: Get Date
        id: get-date
        run: |
          echo ::set-output name=date::$(TZ='Asia/Kolkata' date +"%Y.%m.%d-%H.%M.%S")

      - name: Upload Build Artifact
        uses: ncipollo/release-action@v1.11.2
        with:
          artifacts: "apks/*-output.apk,apks/VancedMicroG.apk"
          token: ${{ secrets.GH_TOKEN }}
          tag: Build-${{ steps.get-date.outputs.date }}
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
      - name: Sleep for 30 seconds
        run: |
          sleep 10
