name: Telegram Upload

on:
  workflow_dispatch: # to trigger manually

jobs:
  tg-upload:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Telegram
        if: ${{ env.HAVE_TELEGRAM_API_ID == 'true' }}
        uses: nikhilbadyal/ghaction-telegram@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          telegram_api_id: $TG_API_ID
          telegram_api_hash: ${{ secrets.TELEGRAM_API_HASH }}
          telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
env:
  HAVE_TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID != '' }}
